name: instanexus
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - biopython=1.85
  - pandas=2.3.1
  - tqdm=4.67.1
  - seaborn=0.13.2
  - matplotlib-base
  - plotly=6.2.0
  - logomaker=0.8
  - networkx
  - mmseqs2
  - sbl::clustalomega
  - gawk
  - wget
  - pip
  - pip:
      - kaleido==0.2.1

