name: instanexus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - ipykernel==6.29.5
      - tqdm==4.67.1
      - pandas==2.3.0
      - networkx==3.2.1
      - biopython==1.85
      - matplotlib==3.9.4
      - seaborn==0.13.2
      - plotly==6.2.0
      - logomaker==0.8.7
      - nbformat>=4.2.0
      - kaleido==1.0.0
      - scikit-learn==1.6.1