name: instanexus
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - clustalo=1.2.3
  - gawk=5.3.1
  - gettext=0.21.0
  - icu=73.1
  - libcxx=17.0.6
  - libexpat=2.7.0
  - libffi=3.4.6
  - libiconv=1.16
  - libidn2=2.3.4
  - libunistring=0.9.10
  - libxml2=2.13.8
  - llvm-openmp=17.0.6
  - mmseqs2=13.45111
  - ncurses=6.5
  - openssl=3.0.16
  - pcre2=10.42
  - pip=25.1.1
  - python=3.9.21
  - readline=8.2
  - setuptools=80.9.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wget=1.25.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - biopython==1.85
      - choreographer==1.0.9
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.58.5
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kaleido==1.0.0
      - kiwisolver==1.4.7
      - logistro==1.1.0
      - logomaker==0.8.7
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - narwhals==1.47.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==2.0.2
      - orjson==3.10.18
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - rpds-py==0.26.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - simplejson==3.20.1
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - wcwidth==0.2.13
      - zipp==3.23.0
