[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "instanexus"
version = "0.2.1"
description = "End-to-end workflow for de novo protein sequencing based on InstaNovo"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
  { name = "Marco Reverenna", email = "marcor@dtu.dk" }
]

keywords = ["proteomics", "bioinformatics", "protein sequencing", "de novo", "assembly", "mass spectrometry"]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

dependencies = [
  "biopython>=1.85",
  "pandas>=2.3.1",
  "tqdm>=4.67.1",
  "seaborn>=0.13.2",
  "matplotlib>=3.8.0",
  "plotly>=6.2.0",
  "logomaker>=0.8",
  "networkx>=3.3",
  "upsetplot"
]

[project.optional-dependencies]
# Optional dependencies to locally build the documentation
docs = [
  "sphinx",
  "sphinx-book-theme",
  "myst-nb",
  "ipywidgets",
  "sphinx-new-tab-link!=0.2.2",
  "jupytext",
  "sphinx-copybutton",
]

# local development options
dev = ["black[jupyter]", "ruff", "pytest", "isort", "jupytext"]

[project.urls]
Homepage = "https://github.com/Multiomics-Analytics-Group/InstaNexus"
Issues = "https://github.com/Multiomics-Analytics-Group/InstaNexus/issues"

[project.scripts]
instanexus = "instanexus.main:cli"

# --- TOOL CONFIGURATIONS ---

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
# Exclude notebooks to avoid linting errors on them
exclude = ["*.ipynb", "docs/source/tutorials/*"]
line-length = 120

[tool.ruff.lint]
# Enable common rules: E (pycodestyle errors), W (warnings), F (pyflakes), B (bugbear)
extend-select = ["E", "W", "F", "B"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"