#!/usr/bin/env python

r"""Clustering module for assembled scaffolds.

 ██████████   ███████████ █████  █████
░░███░░░░███ ░█░░░███░░░█░░███  ░░███ 
 ░███   ░░███░   ░███  ░  ░███   ░███ 
 ░███    ░███    ░███     ░███   ░███ 
 ░███    ░███    ░███     ░███   ░███ 
 ░███    ███     ░███     ░███   ░███ 
 ██████████      █████    ░░████████  
░░░░░░░D░░      ░░░░░      ░░░░░░░░   
     
__authors__ = Marco Reverenna
__copyright__ = Copyright 2025-2026
__research-group__ = DTU Biosustain (Multi-omics Network Analytics) and DTU Bioengineering
__date__ = 03 Nov 2025
__maintainer__ = Marco Reverenna
__email__ = marcor@dtu.dk
__status__ = Dev
"""

import argparse
import logging
import os
import shutil
import subprocess
import pandas as pd
from pathlib import Path
from tempfile import mkdtemp
from Bio import SeqIO
from tqdm import tqdm

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def cluster_fasta_files(
    scaffolds_folder: Path, 
    clustering_dir: Path, 
    min_seq_id: float = 0.85, 
    coverage: float = 0.8
):
    """
    Runs mmseqs easy-cluster on the scaffolds.fasta file.
    
    This is based on the user's provided function, but modified to be
    more robust by targeting only 'scaffolds.fasta' instead of looping.
    """
    cluster_fasta_dir = clustering_dir / "cluster_fasta"
    clustering_dir.mkdir(parents=True, exist_ok=True)
    cluster_fasta_dir.mkdir(exist_ok=True)

    temp_dir = mkdtemp(prefix="mmseqs-")
    
    fasta_path = scaffolds_folder / "scaffolds.fasta"
    if not fasta_path.is_file():
        logger.error(f"Input file not found, skipping clustering: {fasta_path}")
        shutil.rmtree(temp_dir)
        return

    logger.info(f"Running mmseqs easy-cluster on: {fasta_path}")
    base_filename = fasta_path.stem
    prefix = clustering_dir / base_filename

    # Run the mmseqs easy-cluster command
    subprocess.run(
        [
            "mmseqs",
            "easy-cluster",
            str(fasta_path),
            str(prefix),
            temp_dir,
            "--min-seq-id",
            str(min_seq_id),
            "-c",
            str(coverage),
            "--cov-mode",
            "1",
            "-v",
            "1",
        ],
        check=True,
    )

    # Define source and destination paths
    tsv_src = Path(f"{prefix}_cluster.tsv")
    rep_src = Path(f"{prefix}_rep_seq.fasta")
    all_src = Path(f"{prefix}_all_seqs.fasta")

    tsv_dest = clustering_dir / "scaffolds_cluster.tsv"
    rep_dest = clustering_dir / "scaffolds_rep_seq.fasta"
    all_dest = clustering_dir / "scaffolds_all_seqs.fasta"

    # Move and rename the primary output files
    if tsv_src.exists():
        shutil.move(str(tsv_src), tsv_dest)
    if rep_src.exists():
        shutil.move(str(rep_src), rep_dest)
    if all_src.exists():
        shutil.move(str(all_src), all_dest)

    # Clean up other files generated by easy-cluster
    for ext in [".bak", "_clu.fasta", "_clu.index"]:
        extra_file = Path(f"{prefix}{ext}")
        if extra_file.exists():
            extra_file.unlink()

    shutil.rmtree(temp_dir)
    logger.info(f"Clustering tasks completed. TSV saved to: {tsv_dest}")


def process_fasta_and_clusters(fasta_file: Path, scaffolds_folder: Path):
    """
    Reads the cluster.tsv file and splits the original scaffolds.fasta
    into new FASTA files, one for each cluster.
    """
    clustering_dir = scaffolds_folder / "clustering"
    cluster_tsv = clustering_dir / "scaffolds_cluster.tsv"
    cluster_fasta_dir = clustering_dir / "cluster_fasta"
    cluster_fasta_dir.mkdir(exist_ok=True)

    if not cluster_tsv.is_file():
        logger.error(f"Cluster TSV file not found at {cluster_tsv}, skipping.")
        return

    try:
        cluster_df = pd.read_csv(cluster_tsv, sep="\t", header=None, names=["cluster", "contig"])
    except pd.errors.EmptyDataError:
        logger.warning(f"Cluster TSV file is empty: {cluster_tsv}. No clusters to process.")
        return
        
    records = list(SeqIO.parse(fasta_file, "fasta"))
    records_dict = SeqIO.to_dict(records) # Faster lookup
    clusters = cluster_df["cluster"].unique()

    logger.info(f"Splitting {len(records)} sequences into {len(clusters)} clusters.")
    
    width = max(4, len(str(len(clusters)))) # For zfill padding

    for i, cluster_id in enumerate(tqdm(clusters, desc="Processing clusters")):
        contig_ids = cluster_df[cluster_df["cluster"] == cluster_id]["contig"].values
        
        contig_records = []
        for contig_id in contig_ids:
            if contig_id in records_dict:
                contig_records.append(records_dict[contig_id])
            else:
                logger.warning(f"Contig ID {contig_id} not found in {fasta_file.name}")

        cluster_name = f"scaffold_{str(i+1).zfill(width)}.fasta"
        SeqIO.write(contig_records, cluster_fasta_dir / cluster_name, "fasta")

    logger.info(f"All cluster FASTA files created in: {cluster_fasta_dir}")


def main(
    combo_folder: str, 
    run_name: str, 
    assembly_mode: str, 
    conf: float,
    min_seq_id: float,
    coverage: float
):
    """
    Main function to run the clustering script.
    """
    logger.info("--- Starting Step 3: Clustering ---")
    
    combo_folder_path = Path(combo_folder)
    scaffolds_folder_out = combo_folder_path / "scaffolds"
    clustering_out = scaffolds_folder_out / "clustering"

    logger.info(f"Scaffolds Folder (Input): {scaffolds_folder_out}")
    logger.info(f"Clustering Folder (Output): {clustering_out}")

    # --- Step 1: Run the main clustering (mmseqs) ---
    logger.info("Running cluster_fasta_files...")
    cluster_fasta_files(
        scaffolds_folder=scaffolds_folder_out,
        clustering_dir=clustering_out,
        min_seq_id=min_seq_id,
        coverage=coverage
    )
    
    # --- Step 2: Process the cluster results (split FASTA) ---
    logger.info("Running process_fasta_and_clusters...")
    fasta_input = scaffolds_folder_out / "scaffolds.fasta"
    
    if not fasta_input.exists():
        logger.error(f"Input FASTA not found: {fasta_input}")
        raise FileNotFoundError(f"Input FASTA not found: {fasta_input}")
        
    process_fasta_and_clusters(
        fasta_file=fasta_input,
        scaffolds_folder=scaffolds_folder_out
    )
    
    logger.info("--- Step 3: Clustering Completed ---")

def cli():
    """
    Command-line interface (CLI) for the clustering script.
    """
    parser = argparse.ArgumentParser(
        description="Clustering script for assembled scaffolds."
    )
    
    parser.add_argument(
        "--combo-folder",
        type=str,
        required=True,
        help="Path to the 'comb_...' folder (output of the assembly step)."
    )
    parser.add_argument(
        "--run-name",
        type=str,
        required=True,
        help="The base name of the run (e.g., 'bsa')."
    )
    parser.add_argument(
        "--assembly-mode",
        type=str,
        default="greedy",
        help="Assembly mode used (e.g., 'greedy', 'dbg')."
    )
    parser.add_argument(
        "--conf",
        type=float,
        default=0.88,
        help="Confidence score used in the run."
    )
    parser.add_argument(
        "--min-seq-id",
        type=float,
        default=0.85,
        help="Minimum sequence identity for mmseqs (default: 0.85)."
    )
    parser.add_argument(
        "--coverage",
        type=float,
        default=0.8,
        help="Coverage parameter (-c) for mmseqs (default: 0.8)."
    )
    
    args = parser.parse_args()
    
    main(
        combo_folder=args.combo_folder,
        run_name=args.run_name,
        assembly_mode=args.assembly_mode,
        conf=args.conf,
        min_seq_id=args.min_seq_id,
        coverage=args.coverage
    )

if __name__ == "__main__":
    cli()

# python src/instanexus/clustering.py \
#    --combo-folder "outputs/bsa/comb_dbg_c0.9_ks7_ts12_mo5" \
#    --run-name "bsa" \
#    --assembly-mode "dbg" \
#    --conf 0.9